/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignUpRouteImport } from './routes/sign-up'
import { Route as SignInRouteImport } from './routes/sign-in'
import { Route as MyLibraryRouteImport } from './routes/my-library'
import { Route as MethodologyRouteImport } from './routes/methodology'
import { Route as LibraryRouteImport } from './routes/library'
import { Route as CreateRouteImport } from './routes/create'
import { Route as IndexRouteImport } from './routes/index'
import { Route as StoriesStoryIdRouteImport } from './routes/stories.$storyId'
import { Route as SignUpSsoCallbackRouteImport } from './routes/sign-up.sso-callback'
import { Route as SignInSsoCallbackRouteImport } from './routes/sign-in.sso-callback'
import { Route as SSlugRouteImport } from './routes/s.$slug'
import { Route as ApiMayarWebhookRouteImport } from './routes/api/mayar/webhook'
import { Route as ApiMediaStoriesStoryIdImagesIndexRouteImport } from './routes/api/media/stories/$storyId/images/$index'
import { Route as ApiMediaStoriesStoryIdAudioIndexRouteImport } from './routes/api/media/stories/$storyId/audio/$index'

const SignUpRoute = SignUpRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => rootRouteImport,
} as any)
const SignInRoute = SignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const MyLibraryRoute = MyLibraryRouteImport.update({
  id: '/my-library',
  path: '/my-library',
  getParentRoute: () => rootRouteImport,
} as any)
const MethodologyRoute = MethodologyRouteImport.update({
  id: '/methodology',
  path: '/methodology',
  getParentRoute: () => rootRouteImport,
} as any)
const LibraryRoute = LibraryRouteImport.update({
  id: '/library',
  path: '/library',
  getParentRoute: () => rootRouteImport,
} as any)
const CreateRoute = CreateRouteImport.update({
  id: '/create',
  path: '/create',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const StoriesStoryIdRoute = StoriesStoryIdRouteImport.update({
  id: '/stories/$storyId',
  path: '/stories/$storyId',
  getParentRoute: () => rootRouteImport,
} as any)
const SignUpSsoCallbackRoute = SignUpSsoCallbackRouteImport.update({
  id: '/sso-callback',
  path: '/sso-callback',
  getParentRoute: () => SignUpRoute,
} as any)
const SignInSsoCallbackRoute = SignInSsoCallbackRouteImport.update({
  id: '/sso-callback',
  path: '/sso-callback',
  getParentRoute: () => SignInRoute,
} as any)
const SSlugRoute = SSlugRouteImport.update({
  id: '/s/$slug',
  path: '/s/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMayarWebhookRoute = ApiMayarWebhookRouteImport.update({
  id: '/api/mayar/webhook',
  path: '/api/mayar/webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMediaStoriesStoryIdImagesIndexRoute =
  ApiMediaStoriesStoryIdImagesIndexRouteImport.update({
    id: '/api/media/stories/$storyId/images/$index',
    path: '/api/media/stories/$storyId/images/$index',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiMediaStoriesStoryIdAudioIndexRoute =
  ApiMediaStoriesStoryIdAudioIndexRouteImport.update({
    id: '/api/media/stories/$storyId/audio/$index',
    path: '/api/media/stories/$storyId/audio/$index',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/create': typeof CreateRoute
  '/library': typeof LibraryRoute
  '/methodology': typeof MethodologyRoute
  '/my-library': typeof MyLibraryRoute
  '/sign-in': typeof SignInRouteWithChildren
  '/sign-up': typeof SignUpRouteWithChildren
  '/s/$slug': typeof SSlugRoute
  '/sign-in/sso-callback': typeof SignInSsoCallbackRoute
  '/sign-up/sso-callback': typeof SignUpSsoCallbackRoute
  '/stories/$storyId': typeof StoriesStoryIdRoute
  '/api/mayar/webhook': typeof ApiMayarWebhookRoute
  '/api/media/stories/$storyId/audio/$index': typeof ApiMediaStoriesStoryIdAudioIndexRoute
  '/api/media/stories/$storyId/images/$index': typeof ApiMediaStoriesStoryIdImagesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/create': typeof CreateRoute
  '/library': typeof LibraryRoute
  '/methodology': typeof MethodologyRoute
  '/my-library': typeof MyLibraryRoute
  '/sign-in': typeof SignInRouteWithChildren
  '/sign-up': typeof SignUpRouteWithChildren
  '/s/$slug': typeof SSlugRoute
  '/sign-in/sso-callback': typeof SignInSsoCallbackRoute
  '/sign-up/sso-callback': typeof SignUpSsoCallbackRoute
  '/stories/$storyId': typeof StoriesStoryIdRoute
  '/api/mayar/webhook': typeof ApiMayarWebhookRoute
  '/api/media/stories/$storyId/audio/$index': typeof ApiMediaStoriesStoryIdAudioIndexRoute
  '/api/media/stories/$storyId/images/$index': typeof ApiMediaStoriesStoryIdImagesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/create': typeof CreateRoute
  '/library': typeof LibraryRoute
  '/methodology': typeof MethodologyRoute
  '/my-library': typeof MyLibraryRoute
  '/sign-in': typeof SignInRouteWithChildren
  '/sign-up': typeof SignUpRouteWithChildren
  '/s/$slug': typeof SSlugRoute
  '/sign-in/sso-callback': typeof SignInSsoCallbackRoute
  '/sign-up/sso-callback': typeof SignUpSsoCallbackRoute
  '/stories/$storyId': typeof StoriesStoryIdRoute
  '/api/mayar/webhook': typeof ApiMayarWebhookRoute
  '/api/media/stories/$storyId/audio/$index': typeof ApiMediaStoriesStoryIdAudioIndexRoute
  '/api/media/stories/$storyId/images/$index': typeof ApiMediaStoriesStoryIdImagesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/create'
    | '/library'
    | '/methodology'
    | '/my-library'
    | '/sign-in'
    | '/sign-up'
    | '/s/$slug'
    | '/sign-in/sso-callback'
    | '/sign-up/sso-callback'
    | '/stories/$storyId'
    | '/api/mayar/webhook'
    | '/api/media/stories/$storyId/audio/$index'
    | '/api/media/stories/$storyId/images/$index'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/create'
    | '/library'
    | '/methodology'
    | '/my-library'
    | '/sign-in'
    | '/sign-up'
    | '/s/$slug'
    | '/sign-in/sso-callback'
    | '/sign-up/sso-callback'
    | '/stories/$storyId'
    | '/api/mayar/webhook'
    | '/api/media/stories/$storyId/audio/$index'
    | '/api/media/stories/$storyId/images/$index'
  id:
    | '__root__'
    | '/'
    | '/create'
    | '/library'
    | '/methodology'
    | '/my-library'
    | '/sign-in'
    | '/sign-up'
    | '/s/$slug'
    | '/sign-in/sso-callback'
    | '/sign-up/sso-callback'
    | '/stories/$storyId'
    | '/api/mayar/webhook'
    | '/api/media/stories/$storyId/audio/$index'
    | '/api/media/stories/$storyId/images/$index'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CreateRoute: typeof CreateRoute
  LibraryRoute: typeof LibraryRoute
  MethodologyRoute: typeof MethodologyRoute
  MyLibraryRoute: typeof MyLibraryRoute
  SignInRoute: typeof SignInRouteWithChildren
  SignUpRoute: typeof SignUpRouteWithChildren
  SSlugRoute: typeof SSlugRoute
  StoriesStoryIdRoute: typeof StoriesStoryIdRoute
  ApiMayarWebhookRoute: typeof ApiMayarWebhookRoute
  ApiMediaStoriesStoryIdAudioIndexRoute: typeof ApiMediaStoriesStoryIdAudioIndexRoute
  ApiMediaStoriesStoryIdImagesIndexRoute: typeof ApiMediaStoriesStoryIdImagesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sign-up': {
      id: '/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof SignUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-in': {
      id: '/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof SignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-library': {
      id: '/my-library'
      path: '/my-library'
      fullPath: '/my-library'
      preLoaderRoute: typeof MyLibraryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/methodology': {
      id: '/methodology'
      path: '/methodology'
      fullPath: '/methodology'
      preLoaderRoute: typeof MethodologyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/library': {
      id: '/library'
      path: '/library'
      fullPath: '/library'
      preLoaderRoute: typeof LibraryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/create': {
      id: '/create'
      path: '/create'
      fullPath: '/create'
      preLoaderRoute: typeof CreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stories/$storyId': {
      id: '/stories/$storyId'
      path: '/stories/$storyId'
      fullPath: '/stories/$storyId'
      preLoaderRoute: typeof StoriesStoryIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-up/sso-callback': {
      id: '/sign-up/sso-callback'
      path: '/sso-callback'
      fullPath: '/sign-up/sso-callback'
      preLoaderRoute: typeof SignUpSsoCallbackRouteImport
      parentRoute: typeof SignUpRoute
    }
    '/sign-in/sso-callback': {
      id: '/sign-in/sso-callback'
      path: '/sso-callback'
      fullPath: '/sign-in/sso-callback'
      preLoaderRoute: typeof SignInSsoCallbackRouteImport
      parentRoute: typeof SignInRoute
    }
    '/s/$slug': {
      id: '/s/$slug'
      path: '/s/$slug'
      fullPath: '/s/$slug'
      preLoaderRoute: typeof SSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/mayar/webhook': {
      id: '/api/mayar/webhook'
      path: '/api/mayar/webhook'
      fullPath: '/api/mayar/webhook'
      preLoaderRoute: typeof ApiMayarWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/media/stories/$storyId/images/$index': {
      id: '/api/media/stories/$storyId/images/$index'
      path: '/api/media/stories/$storyId/images/$index'
      fullPath: '/api/media/stories/$storyId/images/$index'
      preLoaderRoute: typeof ApiMediaStoriesStoryIdImagesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/media/stories/$storyId/audio/$index': {
      id: '/api/media/stories/$storyId/audio/$index'
      path: '/api/media/stories/$storyId/audio/$index'
      fullPath: '/api/media/stories/$storyId/audio/$index'
      preLoaderRoute: typeof ApiMediaStoriesStoryIdAudioIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface SignInRouteChildren {
  SignInSsoCallbackRoute: typeof SignInSsoCallbackRoute
}

const SignInRouteChildren: SignInRouteChildren = {
  SignInSsoCallbackRoute: SignInSsoCallbackRoute,
}

const SignInRouteWithChildren =
  SignInRoute._addFileChildren(SignInRouteChildren)

interface SignUpRouteChildren {
  SignUpSsoCallbackRoute: typeof SignUpSsoCallbackRoute
}

const SignUpRouteChildren: SignUpRouteChildren = {
  SignUpSsoCallbackRoute: SignUpSsoCallbackRoute,
}

const SignUpRouteWithChildren =
  SignUpRoute._addFileChildren(SignUpRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CreateRoute: CreateRoute,
  LibraryRoute: LibraryRoute,
  MethodologyRoute: MethodologyRoute,
  MyLibraryRoute: MyLibraryRoute,
  SignInRoute: SignInRouteWithChildren,
  SignUpRoute: SignUpRouteWithChildren,
  SSlugRoute: SSlugRoute,
  StoriesStoryIdRoute: StoriesStoryIdRoute,
  ApiMayarWebhookRoute: ApiMayarWebhookRoute,
  ApiMediaStoriesStoryIdAudioIndexRoute: ApiMediaStoriesStoryIdAudioIndexRoute,
  ApiMediaStoriesStoryIdImagesIndexRoute:
    ApiMediaStoriesStoryIdImagesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
